# Generated by Django 4.2.5 on 2023-09-30 17:39

from django.db import migrations, models
import django.db.models.deletion
import livemap.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parking_lot_address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "geolocation",
                    models.JSONField(
                        help_text="Latitude and longitude of a parking lot. Ex.: [49.911848, 16.611212]",
                        validators=[livemap.models.validate_geolocation],
                    ),
                ),
                ("total_spots", models.PositiveIntegerField()),
                ("address", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="livemap.address")),
            ],
        ),
        migrations.CreateModel(
            name="VideoStreamSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stream_source", models.URLField()),
                ("processing_rate", models.PositiveIntegerField(help_text="In seconds.")),
                (
                    "parking_zone",
                    models.JSONField(
                        blank=True, help_text="An array in a format [[[[int, int]], [[int, int]], ...]].", null=True
                    ),
                ),
                (
                    "parking_lot",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="livemap.parkinglot"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Occupancy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occupied_spots", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parking_lot",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="livemap.parkinglot"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city_name", models.CharField(max_length=50)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="livemap.country")),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="livemap.city"),
        ),
    ]
